### ISSUE TITLE
Style Local Notifications

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordSpezi/SpeziScheduler#19]
### Problem

Local notifications are currently based on the title and subtitle of the task that the event is associated with.

### Solution

The styling of the notifications should be customizable.

A suggestion to implement this functionality could be adding a closure or delegate-based configuration in the Scheduler type that allows an application to style the notification based on the task context. An additional possibility would be adding this functionality in the `Task` type.

### Additional context

Any suggestions on the API surface are greatly appreciated. Feel free to use the comment section under this issue to discuss possible ideas and how you can implement that functionality in this module.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by AballahNsour** [comment]
I will work on this problem.
