### ISSUE TITLE
Test Start and End Dates

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordSpezi/SpeziScheduler#21]
### Problem

The current UI and unit test do not include tests to validate that the start and the end date of a task are considered when scheduling or retrieving a task.

### Solution

Add a UI or unit test to validate the start and end date-related functionality in the Scheduler module. This includes scheduling tasks as well as retrieving tasks using a start or end date.

### Additional context

This issue provides a good starting point to get familiar with the Scheduler module by writing a small test case.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by AballahNsour** [comment]
hello I have picked up this issue and I have added the two test

**Comment by PSchmiedmayer** [comment]
@AballahNsour Thank you for taking a look at the issue! Feel free to create a PR and tag us if you have any questions. Always great to see contributions from outside contributors and we are happy to support you in the process!
