### ISSUE TITLE
Improve performance of event scheduling.

### ISSUE THREAD

**Issue by Supereg** [StanfordSpezi/SpeziScheduler#39]
### Problem

Currently, the scheduling of the events of a single task can take several seconds. This results in some delay when opening the app for the first time.

### Solution

Analyze the underlying issue (presumably the scheduling of the notifications) and optimize scheduling of task to be faster (e.g., might show up earlier in UI while notifications are still scheduler).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by PSchmiedmayer** [comment]
My best guess is that this is related to the current mechanism on either how elements are persisted that could take a substantial amount of time, or how the calculations and especially notification registration is performed that can take a substantial amount of time.
